/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AtomsAvatar {
        "imageLink": string;
        "name": string;
    }
    interface AtomsClaps {
        "item": any;
    }
    interface AtomsClapsButton {
        "clapsTotal": number;
        "domId": number;
    }
    interface AtomsTitle {
        "commentBody": string;
        "commentTitle": string;
    }
    interface StatusCard {
    }
}
declare global {
    interface HTMLAtomsAvatarElement extends Components.AtomsAvatar, HTMLStencilElement {
    }
    var HTMLAtomsAvatarElement: {
        prototype: HTMLAtomsAvatarElement;
        new (): HTMLAtomsAvatarElement;
    };
    interface HTMLAtomsClapsElement extends Components.AtomsClaps, HTMLStencilElement {
    }
    var HTMLAtomsClapsElement: {
        prototype: HTMLAtomsClapsElement;
        new (): HTMLAtomsClapsElement;
    };
    interface HTMLAtomsClapsButtonElement extends Components.AtomsClapsButton, HTMLStencilElement {
    }
    var HTMLAtomsClapsButtonElement: {
        prototype: HTMLAtomsClapsButtonElement;
        new (): HTMLAtomsClapsButtonElement;
    };
    interface HTMLAtomsTitleElement extends Components.AtomsTitle, HTMLStencilElement {
    }
    var HTMLAtomsTitleElement: {
        prototype: HTMLAtomsTitleElement;
        new (): HTMLAtomsTitleElement;
    };
    interface HTMLStatusCardElement extends Components.StatusCard, HTMLStencilElement {
    }
    var HTMLStatusCardElement: {
        prototype: HTMLStatusCardElement;
        new (): HTMLStatusCardElement;
    };
    interface HTMLElementTagNameMap {
        "atoms-avatar": HTMLAtomsAvatarElement;
        "atoms-claps": HTMLAtomsClapsElement;
        "atoms-claps-button": HTMLAtomsClapsButtonElement;
        "atoms-title": HTMLAtomsTitleElement;
        "status-card": HTMLStatusCardElement;
    }
}
declare namespace LocalJSX {
    interface AtomsAvatar {
        "imageLink"?: string;
        "name"?: string;
    }
    interface AtomsClaps {
        "item"?: any;
        "onClickLikeButton"?: (event: CustomEvent<any>) => void;
    }
    interface AtomsClapsButton {
        "clapsTotal"?: number;
        "domId"?: number;
        "onButtonClick"?: (event: CustomEvent<Object>) => void;
    }
    interface AtomsTitle {
        "commentBody"?: string;
        "commentTitle"?: string;
    }
    interface StatusCard {
    }
    interface IntrinsicElements {
        "atoms-avatar": AtomsAvatar;
        "atoms-claps": AtomsClaps;
        "atoms-claps-button": AtomsClapsButton;
        "atoms-title": AtomsTitle;
        "status-card": StatusCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "atoms-avatar": LocalJSX.AtomsAvatar & JSXBase.HTMLAttributes<HTMLAtomsAvatarElement>;
            "atoms-claps": LocalJSX.AtomsClaps & JSXBase.HTMLAttributes<HTMLAtomsClapsElement>;
            "atoms-claps-button": LocalJSX.AtomsClapsButton & JSXBase.HTMLAttributes<HTMLAtomsClapsButtonElement>;
            "atoms-title": LocalJSX.AtomsTitle & JSXBase.HTMLAttributes<HTMLAtomsTitleElement>;
            "status-card": LocalJSX.StatusCard & JSXBase.HTMLAttributes<HTMLStatusCardElement>;
        }
    }
}
